apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  annotations:
    extra.apis.kcp.io/compute.workload.kcp.io: "true"
    kcp.io/cluster: 49adf4fn8ks8x43u
    kcp.io/path: root:jn
    workload.kcp.io/skip-default-object-creation: "true"
  creationTimestamp: "2023-03-20T18:37:20Z"
  generation: 5
  name: kubernetes
  resourceVersion: "801"
  uid: 9af84401-21f1-400e-b570-6cd38fb8713b
spec:
  identity:
    secretRef:
      name: kubernetes
      namespace: kcp-system
  latestResourceSchemas:
  - rev-788.deployments.apps
  - rev-789.ingresses.networking.k8s.io
  - rev-774.pods.core
  - rev-770.services.core
status:
  conditions:
  - lastTransitionTime: "2023-03-20T18:37:20Z"
    status: "True"
    type: IdentityValid
  - lastTransitionTime: "2023-03-20T18:37:20Z"
    status: "True"
    type: VirtualWorkspaceURLsReady
  identityHash: b20e9ad1d17024e51df7cd1af743cf403e385c3e890c9e1b16034ee604de7b0e
  virtualWorkspaces:
  - url: https://<kcp-url>:6443/services/apiexport/49adf4fn8ks8x43u/kubernetes
