apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  annotations:
    extra.apis.kcp.io/compute.workload.kcp.io: "true"
    kcp.io/cluster: br3qimk2t1o3jb70
  creationTimestamp: "2023-03-21T17:05:37Z"
  finalizers:
  - apis.kcp.io/apibinding-finalizer
  generation: 1
  labels:
    claimed.internal.apis.kcp.io/2rwzR3UC0Z0lSFUGD5EuXbE1OSTXPKljY8O67v: LstvmbbzVDDOn90ZbhzSQO5U3DMCf88h1pZ
    internal.apis.kcp.io/export: 2rwzR3UC0Z0lSFUGD5EuXbE1OSTXPKljY8O67v
  name: kubernetes
  resourceVersion: "9101"
  uid: ba26edd8-fb9c-4b85-a5e1-e662e882a8ca
spec:
  reference:
    export:
      name: kubernetes
status:
  apiExportClusterName: br3qimk2t1o3jb70
  conditions:
  - lastTransitionTime: "2023-03-21T17:05:37Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-03-21T17:05:37Z"
    status: "True"
    type: APIExportValid
  - lastTransitionTime: "2023-03-21T17:05:37Z"
    status: "True"
    type: BindingUpToDate
  - lastTransitionTime: "2023-03-21T17:05:37Z"
    status: "True"
    type: InitialBindingCompleted
  - lastTransitionTime: "2023-03-21T17:05:37Z"
    status: "True"
    type: PermissionClaimsApplied
  - lastTransitionTime: "2023-03-21T17:05:37Z"
    status: "True"
    type: PermissionClaimsValid
  phase: Bound
